Repository JeanLucGaffud/CSSWENG, pull requests merged in 2025-06, with the labels that each got.

#19 Implement role login authentication
  pfvi-system/app/api/check-auth/route.js
  pfvi-system/app/api/login/route.js
  pfvi-system/app/api/logout/route.js
  pfvi-system/components/auth-check.jsx
  pfvi-system/components/login.jsx
Labels: enhancement

#20 Fixed the cookie async issue
  pfvi-system/app/api/check-auth/route.js
  pfvi-system/app/api/login/route.js
  pfvi-system/app/api/logout/route.js
Labels: hotfix

#22 Logout button for all roles
  pfvi-system/app/driver/page.jsx
  pfvi-system/app/page.jsx
  pfvi-system/app/salesman/page.jsx
  pfvi-system/app/secretary/page.jsx
  pfvi-system/package-lock.json
  pfvi-system/package.json
Labels: enhancement

#38 deleting register.js (my old file i made in sprint 1)
  pfvi-system/app/api/register.js
Labels: trivial

#39 US2 - Sessions Improvement (Remember Me)
  pfvi-system/components/login.jsx
  pfvi-system/components/session_provider.jsx
  pfvi-system/lib/auth.js
  pfvi-system/package-lock.json
  pfvi-system/package.json
Labels: enhancement
